# -*- coding: utf-8 -*-
"""DZ_9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wy-gGG2Pvjbt592NY_-elmGXeSnTf4tk
"""

from collections import defaultdict
# a
def mst_stays_minimal(mst_edges, v, w, c):
    # Строим список смежности
    adj = defaultdict(list)
    for u1, v1, wt in mst_edges:
        adj[u1].append((v1, wt))
        adj[v1].append((u1, wt))

    # Поиск максимального веса на пути v -> w через DFS
    def dfs(current, target, visited, max_edge):
        if current == target:
            return max_edge
        visited.add(current)
        for neighbor, weight in adj[current]:
            if neighbor not in visited:
                res = dfs(neighbor, target, visited, max(max_edge, weight))
                if res is not None:
                    return res
        return None

    max_on_path = dfs(v, w, set(), 0)

    return c >= max_on_path

mst = [
    (0, 1, 2),
    (1, 2, 3),
    (2, 3, 4)
]

print(mst_stays_minimal(mst, 0, 3, 5))
print(mst_stays_minimal(mst, 0, 3, 3))

# b
def update_mst(mst_edges, v, w, c):
    adj = {}
    for a, b, wt in mst_edges:
        adj.setdefault(a, {})[b] = wt
        adj.setdefault(b, {})[a] = wt

    # 2. DFS ищет путь v -> w и запоминает рёбра на пути
    def find_path(cur, target, visited, path_edges):
        if cur == target:
            return True
        visited.add(cur)
        for nb, wt in adj.get(cur, {}).items():
            if nb not in visited:
                path_edges.append((cur, nb, wt))
                if find_path(nb, target, visited, path_edges):
                    return True
                path_edges.pop()
        return False

    path_edges = []
    find_path(v, w, set(), path_edges)

    # Находим самое тяжёлое ребро на пути
    max_edge = max(path_edges, key=lambda e: e[2])

    # Строим новый MST: удаляем max_edge, добавляем новое
    new_mst = []
    for a, b, wt in mst_edges:
        if {a, b} != {max_edge[0], max_edge[1]}:
            new_mst.append((a, b, wt))
    new_mst.append((v, w, c))
    return new_mst


old_mst = [(0, 1, 10), (1, 2, 20), (2, 3, 30)]
new = update_mst(old_mst, 0, 3, 15)
print(new)